#!/usr/bin/env node
// i hope i find time to rewrite this in a better way later
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const REPO_URL = 'https://github.com/smogon/pokemon-showdown.git';
const DIR_NAME = 'pokemon-showdown';

function run(cmd, cwd = process.cwd()) {
  console.log(`\n> ${cmd}`);
  execSync(cmd, {
    cwd,
    stdio: 'inherit',
  });
}

function main() {
  const targetDir = path.join(process.cwd(), DIR_NAME);
console.log('Building pokemon-showdown...');
  if (!fs.existsSync(targetDir)) {
    run(`git clone ${REPO_URL}`);
  } else {
    console.log(`Repo already exists at ${DIR_NAME}, skipping clone`);
  }

  run('npm install', targetDir);
  run('node build', targetDir);


  console.log('\n[DONE] Build setup complete');
}

main();
